name: Feature Request
description: Suggest a new feature or enhancement for ARK-Retro-Forge
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature request does NOT involve downloading ROMs, BIOS, or copyrighted content
          required: true
        - label: This feature request does NOT involve circumventing DRM or copy protection
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - New command
        - Enhancement to existing command
        - Plugin/extension capability
        - Performance improvement
        - Documentation
        - Developer experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the motivation?
      placeholder: I'm trying to do X but currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Add a new command/option that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Provide an example of how this feature would be used
      placeholder: |
        ark-retro-forge new-command --option value
        Expected output: ...
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      description: Which areas would this feature affect? (check all that apply)
      options:
        - label: Core library
        - label: CLI interface
        - label: Plugin system
        - label: Database/caching
        - label: Logging
        - label: External tool integration
        - label: Configuration
        - label: Documentation
        - label: Tests

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical/blocking
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation
